version: '3'

services:
  front:
    container_name: front
    image: matheuspieropan/proposta-web
    ports:
      - "80:80"

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=proposals
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=daniel123

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'my-rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
